### ISSUE TITLE
Expand README to cover installation / usage

### ISSUE THREAD

**Issue by jinnatar** [PaulFreund/i2x#1]
What the title says.

**Comment by PaulFreund** [comment]
I'm sorry I read this so late, I'll do it as soon as I can, probably should have made a npm package from it

**Comment by i-am-at0m** [comment]
Would definitely appreciate this myself.

**Comment by niftylight** [comment]
me, too... Even brief instructions would help ;)

**Comment by PaulFreund** [comment]
Cleaned up a little bit and added a Readme, hope it helps ;)
